# Generated by Django 6.0.6 on 2026-06-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=100)),
                ('main_actor', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('action', '액션'), ('comedy', '코미디'), ('drama', '드라마'), ('romance', '로맨스'), ('thriller', '스릴러'), ('horror', '공포'), ('sf', 'SF'), ('animation', '애니메이션'), ('documentary', '다큐멘터리'), ('fantasy', '판타지')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')])),
                ('running_time', models.PositiveIntegerField(help_text='분 단위로 입력해주세요.')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
