# Generated by Django 6.0.6 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(choices=[(0.5, '0.5점'), (1.0, '1.0점'), (1.5, '1.5점'), (2.0, '2.0점'), (2.5, '2.5점'), (3.0, '3.0점'), (3.5, '3.5점'), (4.0, '4.0점'), (4.5, '4.5점'), (5.0, '5.0점')]),
        ),
    ]
